### PR TITLE
add few questions to security-quiz.ts

### LINKED ISSUE #1135: Adding Security questions to quiz site
### What general issue would you like to create?

What general issue would you like to create?

[developerquiz.org](https://github.com/freeCodeCamp/Developer_Quiz_Site/issues/developerquiz.org) currently has over 1500 quiz questions. We are looking to expand on the security questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of security questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/security-quiz.ts

You can add your own questions to the top of that file.
Please first check to make sure your question doesn't already exist in the file before creating a PR.

Here is an example format for the questions.

```
 {
    Question: "Which of the following is not an Attack model in cryptanalysis?",
    Answer: "CVA (Chosen Vector Attack)",
    Distractor1: "CPA (Chosen Plaintext Attack)",
    Distractor2: "CCA (Chosen Ciphertext Attack)",
    Distractor3: "COA (Ciphertext Only Attack)",
    Explanation: "There is no attack model named CVA (Chosen vector attack).",
    Link: "https://en.wikipedia.org/wiki/Attack_model"
  }
```
For the link field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#).

There are plenty of freeCodeCamp news articles to pull Security questions from:
https://www.freecodecamp.org/news/tag/security

This issue will not be assigned to anyone and will remain open for multiple contributors.
Please do not assign yourself to this issue or close it.

Happy contributing!

### PR DESCRIPTION
**Pull request by srahi904**
Added a set of security-related multiple-choice questions to the security-quiz.ts file. The questions focus on key topics like cryptographic hash functions, quantum-resistant cryptographic algorithms, penetration testing, encryption modes, blockchain hashing algorithms, and cryptographic key lifecycles.

## Summary of changes

 I added some questions to security-quiz.ts about security topics like hash functions, quantum crypto, penetration testing and some other stuff. Each question got right answer and 3 wrong options, also I wrote a small explanation for why the answer is right. And I put a Wikipedia link for more info.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

### CODE REVIEW

**Comment by srahi904** [comment]
Hello , I have added Few questions and raised a PR #1160  Pull Request, can you please check and let me know.  Thank You !

**Review by srahi904 — COMMENTED** [review]
I added some questions to security-quiz.ts about security topics, like hash functions, quantum crypto, penetration testing, and some other stuff. Each question got a right answer and three wrong options, also I wrote a small explanation for why the answer is right. And I put a Wikipedia link for more info.

**Comment by srahi904** [comment]
Hello , I have added Few questions and raised a PR #1160 , please check it and let me Know . Thank You!!

**Review by jdwilkin4 — COMMENTED** [review]
The question, answer and distractor keys should not be quotes.
The format should match what is already in the file

please fix that before a review can take place

**Comment by jdwilkin4** [comment]
HI @srahi904 ! 

I am going to close this PR due to inactivity.
If you would like to still contribute, then feel free to reopen this PR and apply the changes mentioned in the review 👍

**Pull request closed without merging**
