### PR TITLE
Chore: Update cloud-computing-quiz.ts

### PR DESCRIPTION
**Pull request by Jasmine-maryj**
## Summary of changes

Added a new cloud computing question.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

### CODE REVIEW

**Comment by jdwilkin4** [comment]
May I ask why you closed your last PR?
Do you need help with something?

**Comment by Jasmine-maryj** [comment]
Actually, I did not get how to resolve that conflict.

**Comment by Jasmine-maryj** [comment]
Thank you for taking the time to provide feedback and valuable tips.

**Comment by Jasmine-maryj** [comment]
Can I make a pull request again after changing that question as you suggested?

**Pull request closed without merging**
