### PR TITLE
Add two questions

### PR DESCRIPTION
**Pull request by Sin-Sumit**
Both are related to sorted method.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by Sin-Sumit** [comment]
@jdwilkin4 Please review this PR.

**Comment by jdwilkin4** [comment]
This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. 

We already have a question Python's `sorted()` method and we are not looking to add additional ones. 
Before creating a PR, please double check to ensure that similar questions don't already exist in the file 👍

**Comment by Sin-Sumit** [comment]
@jdwilkin4 I looked into the quiz and I search also there was no sorted method question present.
I want to know like how I should check whether it is present or not. ctrl+f or any other options

**Comment by jdwilkin4** [comment]
You can use the global search in your code editor
Screen Shot 2022-10-12 at 11 17 23 PM

Here is the current question in the file:
```
  {
    Question:
      "In Python, what built-in function returns a new sorted list from the items in an iterable?",
    Answer: "sorted()",
    Distractor1: "sorting()",
    Distractor2: "print()",
    Distractor3: "copy()",
    Explanation:
      "The sorted() function returns a new sorted list from the items in an iterable. ",
    Link: "https://www.freecodecamp.org/news/python-sort-list-how-to-order-by-descending-or-ascending/",
  },
```

**Pull request closed without merging**
