### PR TITLE
Removed HTML question for deprecated marquee tag 

### LINKED ISSUE #689: Remove HTML question for deprecated marquee tag
### What general issue would you like to create?

We only want to include questions for active HTML elements.
Let's remove this question on the marquee tag

Here is the file that will need to be edited and here is the question that needs to be removed. 
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/html-quiz.ts#L1663C4-L1673

## How to Contribute

Please read through our [Contributing docs](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md)

This issue is available for assignment only. 
If you are interested in working on this issue, please reply back that you wish to be assigned.
Assignment will be given on a first come basis.
We will only accept PR’s with the person assigned to the issue.

Happy hacking!

### PR DESCRIPTION
**Pull request by Baburao-sanivada**
Removed HTML question for deprecated marquee tag
#689 

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x ] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #689

### CODE REVIEW

**Comment by jdwilkin4** [comment]
Hi @Baburao-sanivada 

Before we can review this PR, please make sure to read through the checklist here and check off the completed items and also make sure to link the issue correctly with the PR so it closes properly

Thank you
Screenshot 2023-10-01 at 9 17 57 AM

**Comment by Baburao-sanivada** [comment]
I Updated my PR please Review it

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by Baburao-sanivada** [comment]
Thank You

**Pull request merged**
