### PR TITLE
docs: Added Three New Quiz Categories to README

### LINKED ISSUE #120: [Docs] - Update README with new categories
### What changes would you like to make in the documentation?

We recently added some new quiz categories which means our README needs to be updated. 
Here is the README file: https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/README.md

Here is what the current README categories section looks like
```md
- HTML 🖊️
- CSS 🎨
- JavaScript ⚙️
- Linux 🐧
- Python 🐍
- Git 📁
- SQL 📊
- IT 🖥️
- and Computer Science Concepts 🤖
```

Please update the categories section of the README to include these new categories:

- Quality Assurance
- Agile
- Security

You don't need to worry about adding emojis next to these new categories. 

If you are interested in working on this issue, then please comment below and it will be assigned to you.

### PR DESCRIPTION
**Pull request by Mustafa-Azad025**
closes #120

### CODE REVIEW

**Comment by Mustafa-Azad025** [comment]
Thank You So Much Mam 😊

**Review by jdwilkin4 — APPROVED** [review]
Hi @Mustafa-Azad025 ! 

Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by Mustafa-Azad025** [comment]
Thank you mam 
Please send some challanging  issues in future So that I Can contribute more to your organization. 😃

**Comment by jdwilkin4** [comment]
freeCodeCamp has more than one repo participate in hacktoberfest this year.
I suggest you look at that main learn repo, if you are interested in contributing more challenging issues.

**Comment by Mustafa-Azad025** [comment]
Ok ma'am ☺️

**Pull request merged**
