### PR TITLE
Added one question about fact related to a python function

### PR DESCRIPTION
**Pull request by ShubhanshuJha**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by ShubhanshuJha** [comment]
I have added a new question in python that is related to the fact of a python function.

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

**Comment by jdwilkin4** [comment]
I applied those changes in an effort to close out the remaining open Hacktoberfest PRs 👍

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by ShubhanshuJha** [comment]
@jdwilkin4 **Thank you**.

**Pull request merged**
