### PR TITLE
fix: remove duplicate JS quiz question 

### LINKED ISSUE #679: Duplicate JavaScript quiz question
### Issue Description
@jdwilkin4 I've noticed that there is a duplicate quiz question in the JavaScript questions list on lines 1596 and 1606.

```
{
  "Question": "In JavaScript, what type of value is an Array?",
  "Answer": "Object",
  "Distractor1": "Array",
  "Distractor2": "Map",
  "Distractor3": "Set",
  "Explanation": "In JavaScript besides primitives types, we have the Object value type. Arrays are a special type of object that represents a collection of similar types of values.",
  "Link": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
}

```

### Steps to Reproduce
1. Open the `javascript-quiz.ts`.
2. Navigate to lines 1596 and 1606.

### Expected Behavior
Each question in the quiz should be unique.

### Actual Behavior
The question on line 1596 is identical to the one on line 1606.

### Suggested Fix
Remove one of the duplicate questions.

### PR DESCRIPTION
**Pull request by Gautam-Hegde**
Checklist:

## Summary of changes

Removed duplicate quiz question bug in the JavaScript module.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #679

### CODE REVIEW

**Comment by jdwilkin4** [comment]
Hi there!

It looks like you created a PR for an issue marked with the `Available for assignment` label.

We will only accept PR's from those who are assigned to that particular issue.

It looks like this issue hasn't been assigned yet, but it is important that we follow the process so we don't have multiple people submitting PR's for the same issue. 

Before any reviews can take place, please read through our contributing docs to learn more about how the process works. 
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md#issues-available-for-contribution

Thank you for your understanding 👍

**Comment by Gautam-Hegde** [comment]
> Hi there!
> 
> It looks like you created a PR for an issue marked with the `Available for assignment` label.
> 
> We will only accept PR's from those who are assigned to that particular issue.
> 
> It looks like this issue hasn't been assigned yet, but it is important that we follow the process so we don't have multiple people submitting PR's for the same issue.
> 
> Before any reviews can take place, please read through our contributing docs to learn more about how the process works. https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md#issues-available-for-contribution
> 
> Thank you for your understanding 👍

Yeah! I made a PR because the issue wasn't assigned to anyone 😅

**Review by jdwilkin4 — APPROVED** [review]
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by jdwilkin4** [comment]
>

**Comment by jdwilkin4** [comment]
> Yeah! I made a PR because the issue wasn't assigned to anyone

In the future, please make sure to ask to be assigned to issues marked with Available for assignment label.
We want to eliminate what happened last year during hacktoberfest where multiple people were trying to work on the same issue and arguing over it.

This makes for a cleaner process. 👍

**Pull request merged**
