### PR TITLE
feat: use pnpm package manager

### LINKED ISSUE #951: [Feature] - Use pnpm as a package manager
### What feature would you like to see?

While it won't change anything majorly, the majority of our repositories use `pnpm` and I've grown accustomed to it. Maybe we can consider migrating this repository to use it too.

### PR DESCRIPTION
**Pull request by a2937**
## Checklist

- [X] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [X] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [X] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [X] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [X] I have provided a summary of my changes.

closes #951

This removes the package-lock.json and replaces it with a pnpm lock file. I would be happy to prevent others from using `npm` or `yarn` with this site but it seemed a little overkill.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
The workflows still uses npm.
So those will need to be updated.

And a couple of the scripts inside the package.json still reference npm.
so those will need to be updated too

**Comment by jdwilkin4** [comment]
Also, the readme and contributing docs should be updated to mention using `pnpm` instead of `npm`
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md

If a contributor wants to use something else, that is technically their choice I guess.
But the docs should be consistent with the package manager we are using.

**Comment by shootermv** [comment]
wanted to ask here...
how about consider to try `bun` tool instead of `pnpm`? (i heard it even faster)

**Comment by jdwilkin4** [comment]
@shootermv 

I vote we stick with `pnpm`.
A lot of the other freeCodeCamp repos use it so it would be consistent with that.
Then in the future, if the other repos start to migrate to using bun then we can reassess then

**Review by jdwilkin4 — COMMENTED** [review]
It looks like the automated error messages and saying there is no pnpm version specified

**Comment by a2937** [comment]
Why is `jsdom` required yet not on the list of dependencies if we're using it?

**Comment by jdwilkin4** [comment]
It looks like `jsdom` is still being included in the devDependecies. 
Screenshot 2024-04-30 at 9 01 16 AM

and it is still referenced in the vite config file and test setup file.

as for the linting issue it looks like updating the deprecated methods here will fix that
and while we are at it, we should removed that unused CATEGORIES name here

```md
/home/runner/work/Developer_Quiz_Site/Developer_Quiz_Site/src/__tests__/Results.test.tsx
  17:5  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated

/home/runner/work/Developer_Quiz_Site/Developer_Quiz_Site/src/__tests__/SelectQuestionsTotal.test.tsx
  11:5  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated

/home/runner/work/Developer_Quiz_Site/Developer_Quiz_Site/src/components/QuizTemplate.tsx
  4:26  warning  'CATEGORIES' is defined but never used  @typescript-eslint/no-unused-vars
```

**Review by jdwilkin4 — APPROVED** [review]
Things look good to me.
Let's merge this in and make sure the deploy works well 👍

**Pull request merged**
