### PR TITLE
Added Freecodecamp related quiz

### PR DESCRIPTION
**Pull request by harmanjot2002**
## Summary of changes

Added Freecodecamp related quiz

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

### CODE REVIEW

**Comment by jdwilkin4** [comment]
Before a review can be done you will need to clean up your branch first because it looks like you are trying to add questions that were already added in your previous PR's 

Here are the steps you will need to do to clean up your forked copy of the project

1. update your main branch
2. update your branch called `harman` by following the directions laid out in this [doc](https://gist.github.com/seLain/8bdf12c7196f3fccafdf067dec2696b2)

Once you have done that, then we can review your PR 👍

**Comment by harmanjot2002** [comment]
> Before a review can be done you will need to clean up your branch first because it looks like you are trying to add questions that were already added in your previous PR's
> 
> Here are the steps you will need to do to clean up your forked copy of the project
> 
> 1. update your main branch
> 2. update your branch called `harman` by following the directions laid out in this [doc](https://gist.github.com/seLain/8bdf12c7196f3fccafdf067dec2696b2)
> 
> Once you have done that, then we can review your PR 👍

My both the branches are updated,kindly verify and review my PR

**Comment by jdwilkin4** [comment]
I still see changes in this PR that should not be here.
That will need to be resolved.

If you look in the Files changed tab, it still lists question in the html and git quizess but that is incorrect because those questions were already merged in your previous PRs

That will need to be cleaned up.

Also, your main branch still says you are 4 commits behind
Screenshot 2023-10-16 at 12 01 52 AM

Also, your `harman` branch still stays 8 commits ahead and 1 commit behind.
Screenshot 2023-10-16 at 12 03 00 AM

In the article, I linked it shows you how to fix that.

If you need help, then I can resolve this issues on my end.
Just let me know 👍

**Comment by jdwilkin4** [comment]
> My both the branches are updated,kindly verify and review my PR

To be clear, you need to update your remote branches

You might have updated your local branches but the remote ones are the issue.

Hope that is clearer

**Comment by harmanjot2002** [comment]
> I still see changes in this PR that should not be here. That will need to be resolved.
> 
> If you look in the Files changed tab, it still lists question in the html and git quizess but that is incorrect because those questions were already merged in your previous PRs
> 
> That will need to be cleaned up.
> 
> Also, your main branch still says you are 4 commits behind Screenshot 2023-10-16 at 12 01 52 AM
> 
> Also, your `harman` branch still stays 8 commits ahead and 1 commit behind. Screenshot 2023-10-16 at 12 03 00 AM
> 
> In the article, I linked it shows you how to fix that.
> 
> If you need help, then I can resolve this issues on my end. Just let me know 👍

Yes,can you please help me in this thing,on my end when I try to do "git pull",it says everything upto date.

**Comment by harmanjot2002** [comment]
can you please make it all ok from your end or tell me what i need to do for that?

**Comment by jdwilkin4** [comment]
For your main branch, you will need to click on sync fork and then update branch

Screenshot 2023-10-16 at 12 06 03 AM


For your harman branch, you will need to follow the directions in the doc I linked here so it syncs up correctly.
https://gist.github.com/seLain/8bdf12c7196f3fccafdf067dec2696b2

It looks like you will have to do a rebase for the harman branch.
If you don't feel comfortable with that, then I can resolve it on my end

**Comment by harmanjot2002** [comment]
> It looks like you will have to do a rebase for the harman branch.
> If you don't feel comfortable with that, then I can resolve it on my end

Yes yes,you can do rebase or whatever you want to do on your end to resolve my issue

**Review by jdwilkin4 — APPROVED** [review]
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by jdwilkin4** [comment]
@harmanjot2002 

It looks like you removed all files and changes from this PR

Let me go into the file and see if I can revert the changes on my end.
Please do not do any changes in the mean time to this PR 👍

**Comment by harmanjot2002** [comment]
> @harmanjot2002
> 
> It looks like you removed all files and changes from this PR
> 
> Let me go into the file and see if I can revert the changes on my end. Please do not do any changes in the mean time to this PR 👍

yes please

**Comment by harmanjot2002** [comment]
I wanted to do one more PR,can u please tell should I do something before that?

**Comment by harmanjot2002** [comment]
Would it work well if I simply delete fok of this repo. from my account and also clone from my local machine and do fork and clone once again and then make new branch for new contributions and pull requests.

**Comment by harmanjot2002** [comment]
> yeah, that works too.

Okay,thank you so much.

**Pull request merged**
