### PR TITLE
Update general-cs-quiz.ts, Added a question on tree traversal concept

### PR DESCRIPTION
**Pull request by dhruvjain896**
## Summary of changes

Added a question in general-cs quiz, the question is based on the concept of tree traversal

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

### CODE REVIEW

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

**Comment by dhruvjain896** [comment]
@jdwilkin4 I have applied all the changes suggested by you.

**Comment by jdwilkin4** [comment]
@dhruvjain896 

The changes look good.
If you can resolve the merge conflicts then it can be approved and merged 👍

**Comment by dhruvjain896** [comment]
@jdwilkin4 I have resolved the merge conflicts

**Pull request merged**
