### PR TITLE
feat: add computer science question

### PR DESCRIPTION
**Pull request by frankiefab100**
## Summary of changes

Added new computer science question

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

### CODE REVIEW

**Review by jdwilkin4 — COMMENTED** [review]
This question would be better suited in the `information-technology` quiz

**Comment by frankiefab100** [comment]
Should I open this PR for this other quiz section?

**Comment by jdwilkin4** [comment]
> Should I open this PR for this other quiz section?

I am not sure I understand your question.

Are you asking if you need to create a new PR? If that is your question, then no you don't need to create a new PR. You can move that question to the IT quiz and apply changes in this PR

**Comment by frankiefab100** [comment]
> > Should I open this PR for this other quiz section?
> 
> I am not sure I understand your question.
> 
> Are you asking if you need to create a new PR? If that is your question, then no you don't need to create a new PR. You can move that question to the IT quiz and apply changes in this PR

Yes, that's what I might. I already created a new PR. I can still fix this PR if that will make the merge process easier

**Comment by jdwilkin4** [comment]
We can close this one since you already opened a new one.
But in the future, it is best to apply review changes to the same PR 👍

**Comment by frankiefab100** [comment]
> We can close this one since you already opened a new one.
> But in the future, it is best to apply review changes to the same PR 👍

Ok, noted.

**Pull request closed without merging**
