### PR TITLE
Added-questions-to-generalcsquiz

### PR DESCRIPTION
**Pull request by vrashankshetty**
## Summary of changes

Added questions to generalcsquiz

## Checklist
- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by jdwilkin4** [comment]
Also, as a sidenote, it looks like you closed a few of your previous PRs.
It looks like your branch is out of sync and that is why you were having issues updating your branch after the reviews.

After this is merged in, then you can go ahead and delete your branch and update the main branch and then create a new branch for any new questions and PR's you would like to create.

Hope that helps

**Comment by vrashankshetty** [comment]
> Congrats on your first contribution to our repository. 🎉 We look forward to future contributions. 👍

Thank you so much,will surely  contribute.

**Comment by vrashankshetty** [comment]
> Also, as a sidenote, it looks like you closed a few of your previous PRs. It looks like your branch is out of sync and that is why you were having issues updating your branch after the reviews.
> 
> After this is merged in, then you can go ahead and delete your branch and update the main branch and then create a new branch for any new questions and PR's you would like to create.
> 
> Hope that helps

Very helpful,
Thank you

**Comment by vrashankshetty** [comment]
> Also, as a sidenote, it looks like you closed a few of your previous PRs. It looks like your branch is out of sync and that is why you were having issues updating your branch after the reviews.
> 
> After this is merged in, then you can go ahead and delete your branch and update the main branch and then create a new branch for any new questions and PR's you would like to create.
> 
> Hope that helps

One more thing ma'am,
It has been merged and i have deleted the branch as you suggested .But Lint check is not yet completed.
will it affect my merge or will it happen on its own.

**Comment by jdwilkin4** [comment]
no, deleting the branch won't affect the merge.
The lint check is there to make sure there are no syntax errors.
You are fine 👍

**Pull request merged**
