### PR TITLE
feat: adding questions for information Technology quiz

### PR DESCRIPTION
**Pull request by Markson17**
## Summary of changes

I added unique questions to the information Technology quiz

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

### CODE REVIEW

**Review by jdwilkin4 — COMMENTED** [review]
Please remove all of the changes you made to the cs quiz file because you already have another open PR that makes the same changes.

**Comment by jdwilkin4** [comment]
@Markson17 

Are you still interested in working on this?

**Comment by Markson17** [comment]
Yes I am, I would update it later today, I'm sorry for the delay.

**Comment by Markson17** [comment]
I have removed all of the changes I made to the cs quiz file since I already have another open PR that makes the same changes.

**Review by jdwilkin4 — APPROVED** [review]

**Pull request merged**
