### PR TITLE
Add security questions on linux file owners and permissions

### PR DESCRIPTION
**Pull request by suryakapurothu**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by suryakapurothu** [comment]
Hello @jdwilkin4 !
This is a new PR I've made to add questions on Linux file permissions to the security-quiz.ts file.
Please review and advise.

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

**Comment by suryakapurothu** [comment]
Hello @jdwilkin4 !
I've made the necessary changes and pushed them here.
Can you please check and revert?

**Comment by suryakapurothu** [comment]
@jdwilkin4 Can you please review the changes made?

**Review by jdwilkin4 — APPROVED** [review]
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
