### PR TITLE
Add new linux quiz question to linux-quiz.ts

### PR DESCRIPTION
**Pull request by Justin-Quinn51**
## Summary of changes

#16 

Contributed a new question about Linux for use in the FCC Developer Quiz.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by Justin-Quinn51** [comment]
Just had a quick question @jdwilkin4. This latest contribution isn't counting toward Hacktoberfest according to my profile.

I see you added the "hacktoberfest-accepted" label, and my other contribution didn't seem to have any issues being recognized. Do you have any idea why that might be?

**Comment by jdwilkin4** [comment]
I would suggest reaching out to hacktoberfest directly because we haven't changed anything on our end with the repo. 👍

**Comment by Justin-Quinn51** [comment]
Looks like it resolved itself. Thanks for your help @jdwilkin4 :)

**Pull request merged**
