### PR TITLE
Add questions

### PR DESCRIPTION
**Pull request by suryakapurothu**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by suryakapurothu** [comment]
@jdwilkin4 Made the necessary changes mentioned for #207

**Comment by suryakapurothu** [comment]
@jdwilkin4 Can you please review the changes made?

**Comment by jdwilkin4** [comment]
@suryakapurothu 

I am still at work and will get to your PR during my next break.

A big part of open source is learning the workflow and working with maintainers.
A lot of us maintainers have other repos we are involved with as well as full time dev jobs. We review PR's during breaks and off work hours. 
It is important to be patient with reviews because maintainers will get to it when they can.
It is also good practice for on the job as a developer because often times PR's will sit there for a hours and sometimes days before a review if it is a larger feature request. 

Thanks for understanding 👍

**Comment by suryakapurothu** [comment]
@jdwilkin4 Thank you for the patient reply.
I will try and learn to be patient when working on open-sourcing.
Thank you for being a constructive mentor.

I Respect your work!!

**Comment by jdwilkin4** [comment]
I am going to go ahead and close this PR since all of the questions in the PR already exist in the codebase. 
It also looks like your branch is out of date because I see a lot of older commits from a few days ago that were already merged.

Typically with branches you would only use them for a specific PR and then when that PR is merged you would delete the branch.
I would suggest you delete this branch, make sure your `main` branch is up to date and then create a new branch for each new PR you are interested in creating.

**Pull request closed without merging**
